[package]
name = "pirate-ffi-native"
version = "0.3.7"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[features]
default = ["embedded-sapling-params"]
embedded-sapling-params = ["pirate-wallet-service/embedded-sapling-params"]

[dependencies]
pirate-wallet-service = { path = "../pirate-wallet-service", default-features = false }

serde_json = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"
